name: "CI"

on:
  push:
    branches:
      - master

jobs:
  semrel:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-bump-patch-version: true
